package sap_api_input_reader

type EC_MC struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	Document      struct {
		DocumentNo     string `json:"document_no"`
		DeliverTo      string `json:"deliver_to"`
		Quantity       string `json:"quantity"`
		PickedQuantity string `json:"picked_quantity"`
		Price          string `json:"price"`
		Batch          string `json:"batch"`
	} `json:"document"`
	ProductionOrder struct {
		DocumentNo           string `json:"document_no"`
		Status               string `json:"status"`
		DeliverTo            string `json:"deliver_to"`
		Quantity             string `json:"quantity"`
		CompletedQuantity    string `json:"completed_quantity"`
		PlannedStartDate     string `json:"planned_start_date"`
		PlannedValidatedDate string `json:"planned_validated_date"`
		ActualStartDate      string `json:"actual_start_date"`
		ActualValidatedDate  string `json:"actual_validated_date"`
		Batch                string `json:"batch"`
		Work                 struct {
			WorkNo                   string `json:"work_no"`
			Quantity                 string `json:"quantity"`
			CompletedQuantity        string `json:"completed_quantity"`
			ErroredQuantity          string `json:"errored_quantity"`
			Component                string `json:"component"`
			PlannedComponentQuantity string `json:"planned_component_quantity"`
			PlannedStartDate         string `json:"planned_start_date"`
			PlannedStartTime         string `json:"planned_start_time"`
			PlannedValidatedDate     string `json:"planned_validated_date"`
			PlannedValidatedTime     string `json:"planned_validated_time"`
			ActualStartDate          string `json:"actual_start_date"`
			ActualStartTime          string `json:"actual_start_time"`
			ActualValidatedDate      string `json:"actual_validated_date"`
			ActualValidatedTime      string `json:"actual_validated_time"`
		} `json:"work"`
	} `json:"production_order"`
	APISchema      string `json:"api_schema"`
	MaterialCode   string `json:"material_code"`
	Plant_Supplier string `json:"plant/supplier"`
	Stock          string `json:"stock"`
	DocumentType   string `json:"document_type"`
	DocumentNo     string `json:"document_no"`
	PlannedDate    string `json:"planned_date"`
	ValidatedDate  string `json:"validated_date"`
	Deleted        bool   `json:"deleted"`
}

type SDC struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	PlannedOrder  struct {
		PlannedOrder                   string      `json:"PlannedOrder"`
		PlannedOrderType               string      `json:"PlannedOrderType"`
		PlannedOrderProfile            string      `json:"PlannedOrderProfile"`
		Material                       string      `json:"Material"`
		MaterialName                   string      `json:"MaterialName"`
		ProductionPlant                string      `json:"ProductionPlant"`
		MRPPlant                       string      `json:"MRPPlant"`
		MRPArea                        string      `json:"MRPArea"`
		ProductionVersion              string      `json:"ProductionVersion"`
		MaterialProcurementCategory    string      `json:"MaterialProcurementCategory"`
		MaterialProcurementType        string      `json:"MaterialProcurementType"`
		StorageLocation                string      `json:"StorageLocation"`
		BaseUnit                       string      `json:"BaseUnit"`
		TotalQuantity                  int         `json:"TotalQuantity"`
		PlndOrderPlannedScrapQty       int         `json:"PlndOrderPlannedScrapQty"`
		GoodsReceiptQty                int         `json:"GoodsReceiptQty"`
		IssuedQuantity                 int         `json:"IssuedQuantity"`
		PlndOrderPlannedStartDate      string      `json:"PlndOrderPlannedStartDate"`
		PlndOrderPlannedStartTime      string      `json:"PlndOrderPlannedStartTime"`
		PlndOrderPlannedEndDate        string      `json:"PlndOrderPlannedEndDate"`
		PlndOrderPlannedEndTime        string      `json:"PlndOrderPlannedEndTime"`
		PlannedOrderOpeningDate        string      `json:"PlannedOrderOpeningDate"`
		PlannedOrderLastChangeDateTime string      `json:"PlannedOrderLastChangeDateTime"`
		ProductionStartDate            string      `json:"ProductionStartDate"`
		ProductionEndDate              string      `json:"ProductionEndDate"`
		SalesOrder                     string      `json:"SalesOrder"`
		SalesOrderItem                 string      `json:"SalesOrderItem"`
		Customer                       string      `json:"Customer"`
		WBSElementInternalID           string      `json:"WBSElementInternalID"`
		WBSElementExternalID           string      `json:"WBSElementExternalID"`
		WBSDescription                 string      `json:"WBSDescription"`
		AccountAssignmentCategory      string      `json:"AccountAssignmentCategory"`
		Reservation                    string      `json:"Reservation"`
		PlannedOrderLongText           string      `json:"PlannedOrderLongText"`
		MRPController                  string      `json:"MRPController"`
		ProductionSupervisor           string      `json:"ProductionSupervisor"`
		PurchasingGroup                string      `json:"PurchasingGroup"`
		PurchasingOrganization         string      `json:"PurchasingOrganization"`
		FixedSupplier                  string      `json:"FixedSupplier"`
		PurchasingDocument             string      `json:"PurchasingDocument"`
		PurchasingDocumentItem         string      `json:"PurchasingDocumentItem"`
		SupplierName                   string      `json:"SupplierName"`
		PlannedOrderIsFirm             bool        `json:"PlannedOrderIsFirm"`
		PlannedOrderIsConvertible      bool        `json:"PlannedOrderIsConvertible"`
		PlannedOrderBOMIsFixed         bool        `json:"PlannedOrderBOMIsFixed"`
		PlannedOrderCapacityIsDsptchd  bool        `json:"PlannedOrderCapacityIsDsptchd"`
		CapacityRequirement            string      `json:"CapacityRequirement"`
		BillOfOperationsVariant        string      `json:"BillOfOperationsVariant"`
		CapacityRequirementOrigin      string      `json:"CapacityRequirementOrigin"`
		BillOfOperationsType           string      `json:"BillOfOperationsType"`
		BillOfOperationsGroup          string      `json:"BillOfOperationsGroup"`
		LastScheduledDate              string      `json:"LastScheduledDate"`
		ScheduledBasicEndDate          string      `json:"ScheduledBasicEndDate"`
		ScheduledBasicEndTime          string      `json:"ScheduledBasicEndTime"`
		ScheduledBasicStartDate        string      `json:"ScheduledBasicStartDate"`
		ScheduledBasicStartTime        string      `json:"ScheduledBasicStartTime"`
		SchedulingType                 string      `json:"SchedulingType"`
		Component                      struct {
			Reservation                    string      `json:"Reservation"`
			ReservationItem                string      `json:"ReservationItem"`
			BOMItem                        string      `json:"BOMItem"`
			BOMItemDescription             string      `json:"BOMItemDescription"`
			BillOfMaterialCategory         string      `json:"BillOfMaterialCategory"`
			BOMItemSorter                  string      `json:"BOMItemSorter"`
			BillOfMaterialItemNumber       string      `json:"BillOfMaterialItemNumber"`
			BillOfMaterialInternalID       string      `json:"BillOfMaterialInternalID"`
			BillOfMaterialVariant          string      `json:"BillOfMaterialVariant"`
			BOMItemCategory                string      `json:"BOMItemCategory"`
			Material                       string      `json:"Material"`
			MatlCompRequirementDate        string      `json:"MatlCompRequirementDate"`
			GoodsMovementEntryQty          int         `json:"GoodsMovementEntryQty"`
			EntryUnit                      string      `json:"EntryUnit"`
			RequiredQuantity               int         `json:"RequiredQuantity"`
			BaseUnit                       string      `json:"BaseUnit"`
			WithdrawnQuantity              int         `json:"WithdrawnQuantity"`
			DebitCreditCode                string      `json:"DebitCreditCode"`
			ComponentScrapInPercent        float64     `json:"ComponentScrapInPercent"`
			QuantityIsFixed                bool        `json:"QuantityIsFixed"`
			Plant                          string      `json:"Plant"`
			StorageLocation                string      `json:"StorageLocation"`
			SupplyArea                     string      `json:"SupplyArea"`
			MRPController                  string      `json:"MRPController"`
			PlannedOrderLastChangeDateTime string      `json:"PlannedOrderLastChangeDateTime"`
		} `json:"Component"`
	} `json:"PlannedOrder"`
	APISchema      string   `json:"api_schema"`
	Accepter       []string `json:"accepter"`
	PlannedOrderNo string   `json:"planned_order"`
	Deleted        bool     `json:"deleted"`
}
